from core.utils import *

# =========================================================
# CIPHER 12 — SKINNY-128-128  (Beierle et al., CRYPTO 2016)
# =========================================================
# Tweakable SPN. 128-bit block, 128-bit tweakey (key only, no tweak here).
# State: 4×4 byte array (16 bytes).
#
# Round function (repeated `rounds` times):
#   SubCells    : 8-bit S-box applied to each state byte
#   AddConstants: XOR 6-bit LFSR round constant into bytes 0, 4, 8
#   AddRoundKey : XOR first 8 bytes of tweakey into state rows 0–1
#   ShiftRows   : row i rotated left by i positions (same direction as AES)
#   MixColumns  : SKINNY-specific linear layer (NOT the AES MixColumns)
#                 Matrix M over GF(2):
#                   row0' = row0 ^ row2 ^ row3
#                   row1' = row0
#                   row2' = row1 ^ row2
#                   row3' = row0 ^ row2
#   Key schedule: permute all 16 tweakey cells by PT each round
#
# PT permutation (cell indices 0..15, row-major):
#   [9, 15, 8, 13, 10, 14, 12, 11, 0, 1, 2, 3, 4, 5, 6, 7]
#
# S-box: SKINNY-128-specific 8-bit S-box (NOT the AES S-box).
#        It is a bijection on {0..255} — verified in _skinny_unit_tests().
#
# Reference: Beierle et al., "The SKINNY Family of Block Ciphers and
#            Its Low-Latency Variant MANTIS", CRYPTO 2016, LNCS 9815.
# =========================================================

# 8-bit S-box from the SKINNY-128 specification
_SKINNY128_SBOX = [
    0x65,0x4c,0x6a,0x42,0x4b,0x63,0x43,0x6b,0x55,0x75,0x5a,0x7a,0x53,0x73,0x5b,0x7b,
    0x35,0x8c,0x3a,0x81,0x89,0x33,0x80,0x3b,0x95,0x25,0x98,0x2a,0x90,0x23,0x99,0x2b,
    0xe5,0xcc,0xe8,0xc1,0xc9,0xe0,0xc0,0xe9,0xd5,0xf5,0xd8,0xf8,0xd0,0xf0,0xd9,0xf9,
    0xa5,0x1c,0xa8,0x12,0x1b,0xa0,0x13,0xa9,0x05,0xb5,0x0a,0xb8,0x03,0xb0,0x0b,0xb9,
    0x32,0x88,0x3c,0x85,0x8d,0x30,0x84,0x3d,0x92,0x22,0x9c,0x2c,0x94,0x24,0x9d,0x2d,
    0x62,0x4a,0x6c,0x45,0x4d,0x60,0x44,0x6d,0x52,0x72,0x5c,0x7c,0x54,0x74,0x5d,0x7d,
    0xa1,0x1a,0xac,0x15,0x1d,0xa4,0x14,0xad,0x02,0xb1,0x0c,0xbc,0x04,0xb4,0x0d,0xbd,
    0xe1,0xc8,0xec,0xc5,0xcd,0xe4,0xc4,0xed,0xd1,0xf1,0xdc,0xfc,0xd4,0xf4,0xdd,0xfd,
    0x36,0x8e,0x38,0x82,0x8b,0x34,0x83,0x39,0x96,0x26,0x9a,0x28,0x91,0x21,0x9b,0x29,
    0x66,0x4e,0x68,0x41,0x49,0x64,0x40,0x69,0x56,0x76,0x58,0x78,0x50,0x70,0x59,0x79,
    0xa6,0x1e,0xaa,0x11,0x19,0xa3,0x10,0xab,0x06,0xb6,0x08,0xba,0x01,0xb3,0x09,0xbb,
    0xe6,0xce,0xea,0xc2,0xcb,0xe3,0xc3,0xeb,0xd6,0xf6,0xda,0xfa,0xd3,0xf3,0xdb,0xfb,
    0x31,0x8a,0x3e,0x86,0x8f,0x37,0x87,0x3f,0x93,0x20,0x9e,0x2e,0x97,0x27,0x9f,0x2f,
    0x61,0x48,0x6e,0x46,0x4f,0x67,0x47,0x6f,0x51,0x71,0x5e,0x7e,0x57,0x77,0x5f,0x7f,
    0xa2,0x18,0xae,0x16,0x1f,0xa7,0x17,0xaf,0x00,0xb2,0x0e,0xbe,0x07,0xb7,0x0f,0xbf,
    0xe2,0xca,0xee,0xc6,0xcf,0xe7,0xc7,0xef,0xd2,0xf2,0xde,0xfe,0xd7,0xf7,0xdf,0xff,
]

# Tweakey cell permutation applied every round to all 16 cells (row-major)
_SKINNY_PT = [9, 15, 8, 13, 10, 14, 12, 11, 0, 1, 2, 3, 4, 5, 6, 7]


def skinny128_encrypt(P: bytes, rounds: int, key: bytes, **_) -> bytes:
    """
    SKINNY-128-128 reduced-round encryption.

    Parameters
    ----------
    P      : 16-byte plaintext
    rounds : number of rounds to apply (1 ≤ rounds ≤ 40 per spec)
    key    : 16-byte key (used as the full 128-bit tweakey; no tweak)

    Returns
    -------
    16-byte ciphertext (state bytes in row-major order)

    Implementation notes
    --------------------
    Round constants are generated by a 6-bit LFSR with initial value 1.
    Feedback polynomial: bit5 XOR bit4, shifted in at LSB.
    The constant is split across column 0:
        byte 0  ← rc6[3:0]   (lower 4 bits)
        byte 4  ← rc6[5:4]   (upper 2 bits)
        byte 8  ← 0x02       (always 2, as per spec)

    MixColumns applies column-by-column to the 4×4 state:
        new_r0 = r0 ^ r2 ^ r3
        new_r1 = r0
        new_r2 = r1 ^ r2
        new_r3 = r0 ^ r2
    where r0..r3 are the bytes at rows 0–3 of the current column.
    """
    state = list(P)      # 16 bytes, row-major 4×4
    tk    = list(key)    # 16-byte tweakey

    rc6 = 1              # 6-bit LFSR; spec initialises to 1

    for _ in range(rounds):

        # ── SubCells ──────────────────────────────────────────────────────
        state = [_SKINNY128_SBOX[b] for b in state]

        # ── AddConstants ──────────────────────────────────────────────────
        # Split rc6 into two nibble-level constants and XOR into column 0
        c0 =  rc6       & 0x0F   # bits [3:0]
        c1 = (rc6 >> 4) & 0x03   # bits [5:4]
        state[0] ^= c0
        state[4] ^= c1
        state[8] ^= 0x02

        # Advance LFSR: feedback = bit5 XOR bit4, shift left by 1
        feedback = ((rc6 >> 5) ^ (rc6 >> 4)) & 1
        rc6 = ((rc6 << 1) | feedback) & 0x3F

        # ── AddRoundKey ───────────────────────────────────────────────────
        # Only rows 0 and 1 of the tweakey are XOR'd into the state
        for i in range(8):
            state[i] ^= tk[i]

        # ── ShiftRows ─────────────────────────────────────────────────────
        # Row 0 (bytes 0–3)  : no change
        # Row 1 (bytes 4–7)  : cyclic left shift by 1
        state[4], state[5], state[6], state[7] = \
            state[5], state[6], state[7], state[4]
        # Row 2 (bytes 8–11) : cyclic left shift by 2
        state[8],  state[9],  state[10], state[11] = \
            state[10], state[11], state[8],  state[9]
        # Row 3 (bytes 12–15): cyclic left shift by 3
        state[12], state[13], state[14], state[15] = \
            state[15], state[12], state[13], state[14]

        # ── MixColumns ────────────────────────────────────────────────────
        # Applied independently to each of the 4 columns
        for c in range(4):
            r0 = state[c]
            r1 = state[4  + c]
            r2 = state[8  + c]
            r3 = state[12 + c]
            state[c]      = r0 ^ r2 ^ r3
            state[4  + c] = r0
            state[8  + c] = r1 ^ r2
            state[12 + c] = r0 ^ r2

        # ── Key schedule ──────────────────────────────────────────────────
        tk = [tk[_SKINNY_PT[i]] for i in range(16)]

    return bytes(state)